# 端口
server.port= 6101
# 项目名称
spring.application.name= blog

# mybatis
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.xu.blog.domain
# 开启驼峰命名
mybatis.configuration.map-underscore-to-camel-case=true
# 日志
logging.level.com.xu.blog=debug


# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&useUnicode=true&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=admin123456
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# 数据库连接池配置
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.initialSize=5
spring.datasource.minIdle=10
spring.datasource.maxActive=200
spring.datasource.maxWait=60000
spring.datasource.timeBetweenEvictionRunsMillis=60000
spring.datasource.minEvictableIdleTimeMillis=300000
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false

# MyBatis-Plus配置
mybatis-plus.configuration-manager.type=org.mybatisplus.core.configuration.ConfigurationTypeEnum.XML
mybatis-plus.configuration-manager.map-underscore-to-camel-case=true
mybatis-plus.configuration-manager.global-config-type=org.mybatisplus.core.configuration.GlobalConfigTypeEnum.CONVERT_WHITESPACE_TO_UNDERSCORE

# liquibase配置
spring.liquibase.change-log = classpath:liquibase/master.xml
